### PR TITLE
feat: add volumes / fix issue with port

### PR DESCRIPTION
**Pull request by Mattchewone**
# Pull Request Template for Helm Chart

## Description

Add optional volumes & fix issue with exposed port from deployment.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Tested locally on a deployed K3s instance

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

## Additional Information

- **Does this change introduce any new Kubernetes resource types?** (No)
  If yes, please list them:

- **Does this change modify any existing Kubernetes resource types?** (Yes)
  If yes, please describe the modifications:
Added volumeMounts for uploads

- **Are there any changes to the values.yaml file?** (No)
  If yes, please describe the changes and their purpose:

- **Does this change require any specific Kubernetes permissions or RBAC changes?** (No)
  If yes, please describe the required permissions:

- **Are there any changes to chart dependencies?** (No)
  If yes, please list the changes:

- **Have you updated the CHANGELOG.md file?** (No)

## Additional context

Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by jamesread** [comment]
This LGTM, I've sent it to CI :-) Thanks very much @Mattchewone .

**Comment by jamesread** [comment]
Hey @Mattchewone , looks like the job failed, needing a version bump. 

It's a bit weird how that works - I didn't set that bit up, and I'll try and fix the job later. Would you mind just bumping to 1.0.4 in the chart.yaml to see if that fixes the job?

**Comment by Mattchewone** [comment]
> Hey @Mattchewone , looks like the job failed, needing a version bump.
> 
> It's a bit weird how that works - I didn't set that bit up, and I'll try and fix the job later. Would you mind just bumping to 1.0.4 in the chart.yaml to see if that fixes the job?

Ah ok, sure let me try that.

**Comment by timoa** [comment]
Great PR! I tried it, and it fixed the issue with the app loading on the wrong port (3000 instead of 5000).

@Mattchewone Can you please, add the following values into the `values.yaml` file?

```helm
extraVolumes: []
extraVolumeMounts: []
```

Without, we get two issues with Helm-Intellisense:

```bash
Value not defined
postiz-deployment.yaml(42, 24): .Values.extraVolumeMounts
```

```bash
Value not defined
postiz-deployment.yaml(68, 20): .Values.extraVolumes
```

**Comment by jamesread** [comment]
I'd be happy to merge this now, but @Mattchewone , could you consider @timoa 's comments please? I'm indifferent (don't mind) about adding them, I think.

**Comment by Mattchewone** [comment]
@timoa / @jamesread sorry I was away so couldn't respond. 

I've updated. Hopefully this resolves any issues with the linter.

**Comment by jamesread** [comment]
LGTM, merging :-)

**Pull request merged**
